### ISSUE TITLE
ERROR: Unable to receive message from FDR 0x19d8ab0 (-2). 0/2 bytes

### ISSUE THREAD

**Issue by masckmaster2007** [marijuanARM/futurerestore#128]
iPhone 8 256GB Black restoring from iOS 16 to 15.1. Device was recently restored, didn't set a passcode.

Command `"/home/ubuntu/FutureRestoreGUI/extracted/futurerestore" --apticket "/media/ubuntu/2TB/downgrading/_iPhone10,4_d201ap_15.1-19B74.shsh2" --custom-latest-buildid "19G69" --custom-latest-beta --latest-sep --latest-baseband "/media/ubuntu/2TB/downgrading/iPhone_4.7_P3_15.1_19B74_Restore.ipsw"`

`Finished downloading the latest firmware components!
Found device in Recovery mode
Device already in recovery mode
Found device in Recovery mode
Identified device as d201ap, iPhone10,4
Extracting BuildManifest from iPSW
Product version: 15.1
Product build: 19B74 Major: 19
Device supports Image4: true
Got ApNonce from device: 27 32 5c 82 58 be 46 e6 9d 9e e5 7f a9 a8 fb c2 8b 87 3d f4 34 e5 e7 02 a8 b2 79 99 55 11 38 ae 
checking if the APTicket is valid for this restore...
Verified ECID in APTicket matches the device's ECID
checking if the APTicket is valid for this restore...
Verified ECID in APTicket matches the device's ECID
[IMG4TOOL] checking buildidentity 0:
[IMG4TOOL] checking buildidentity matches board ... NO
[IMG4TOOL] checking buildidentity 1:
[IMG4TOOL] checking buildidentity matches board ... NO
[IMG4TOOL] checking buildidentity 2:
[IMG4TOOL] checking buildidentity matches board ... YES
[IMG4TOOL] checking buildidentity has all required hashes:
[IMG4TOOL] checking hash for "AOP"                     OK (untrusted)
[IMG4TOOL] checking hash for "AVE"                     OK (found "avef" with matching hash)
[IMG4TOOL] checking hash for "Ap,SystemVolumeCanonicalMetadata"OK (found "msys" with matching hash)
[IMG4TOOL] checking hash for "AppleLogo"               OK (found "logo" with matching hash)
[IMG4TOOL] checking hash for "AudioCodecFirmware"      OK (untrusted)
[IMG4TOOL] checking hash for "BasebandFirmware"        IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "BatteryCharging0"        OK (found "chg0" with matching hash)
[IMG4TOOL] checking hash for "BatteryCharging1"        OK (found "chg1" with matching hash)
[IMG4TOOL] checking hash for "BatteryFull"             OK (found "batF" with matching hash)
[IMG4TOOL] checking hash for "BatteryLow0"             OK (found "bat0" with matching hash)
[IMG4TOOL] checking hash for "BatteryLow1"             OK (found "bat1" with matching hash)
[IMG4TOOL] checking hash for "BatteryPlugin"           OK (found "glyP" with matching hash)
[IMG4TOOL] checking hash for "DeviceTree"              OK (found "dtre" with matching hash)
[IMG4TOOL] checking hash for "ISP"                     OK (found "ispf" with matching hash)
[IMG4TOOL] checking hash for "KernelCache"             OK (found "krnl" with matching hash)
[IMG4TOOL] checking hash for "LLB"                     OK (found "illb" with matching hash)
[IMG4TOOL] checking hash for "Liquid"                  OK (found "liqd" with matching hash)
[IMG4TOOL] checking hash for "Multitouch"              OK (untrusted)
[IMG4TOOL] checking hash for "OS"                      OK (found "rosi" with matching hash)
[IMG4TOOL] checking hash for "RecoveryMode"            OK (found "recm" with matching hash)
[IMG4TOOL] checking hash for "RestoreDeviceTree"       OK (found "rdtr" with matching hash)
[IMG4TOOL] checking hash for "RestoreKernelCache"      OK (found "rkrn" with matching hash)
[IMG4TOOL] checking hash for "RestoreLogo"             OK (found "rlgo" with matching hash)
[IMG4TOOL] checking hash for "RestoreRamDisk"          OK (found "rdsk" with matching hash)
[IMG4TOOL] checking hash for "RestoreSEP"              OK (found "rsep" with matching hash)
[IMG4TOOL] checking hash for "RestoreTrustCache"       OK (found "rtsc" with matching hash)
[IMG4TOOL] checking hash for "SE,UpdatePayload"        IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "SEP"                     OK (found "sepi" with matching hash)
[IMG4TOOL] checking hash for "StaticTrustCache"        OK (found "trst" with matching hash)
[IMG4TOOL] checking hash for "SystemVolume"            OK (found "isys" with matching hash)
[IMG4TOOL] checking hash for "ftap"                    IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "ftsp"                    IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "iBEC"                    OK (found "ibec" with matching hash)
[IMG4TOOL] checking hash for "iBSS"                    OK (found "ibss" with matching hash)
[IMG4TOOL] checking hash for "iBoot"                   OK (found "ibot" with matching hash)
[IMG4TOOL] checking hash for "rfta"                    IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "rfts"                    IGN (no digest in BuildManifest)
Verified APTicket to be valid for this restore
Variant: Customer Erase Install (IPSW)
This restore will erase all device data.
Using cached filesystem from '/media/ubuntu/DIMI2TB/downgrading/iPhone_4.7_P3_15.1_19B74_Restore/018-58566-091.dmg'
Extracting iBEC.d20.RELEASE.im4p (Firmware/dfu/iBEC.d20.RELEASE.im4p)...
Personalizing IMG4 component iBEC...
Sending iBEC (1079651 bytes)...
Getting SepNonce in recovery mode... 92 35 04 6c 4d 83 a6 9c b9 3e a5 47 27 70 b5 b4 fb 0a e3 de 
Getting ApNonce in recovery mode... 27 32 5c 82 58 be 46 e6 9d 9e e5 7f a9 a8 fb c2 8b 87 3d f4 34 e5 e7 02 a8 b2 79 99 55 11 38 ae 
Recovery Mode Environment:
iBoot build-version=iBoot-7429.42.2
iBoot build-style=RELEASE
Sending RestoreLogo...
Extracting applelogo@2x~iphone.im4p (Firmware/all_flash/applelogo@2x~iphone.im4p)...
Personalizing IMG4 component RestoreLogo...
Sending RestoreLogo (13819 bytes)...
ramdisk-size=0x20000000
Extracting 018-58213-095.dmg (018-58213-095.dmg)...
Personalizing IMG4 component RestoreRamDisk...
Sending RestoreRamDisk (112570008 bytes)...
Extracting AppleAVE2FW_H10.im4p (Firmware/ave/AppleAVE2FW_H10.im4p)...
Personalizing IMG4 component AVE...
Sending AVE (1047997 bytes)...
Extracting adc-nike-d20.im4p (Firmware/isp_bni/adc-nike-d20.im4p)...
Personalizing IMG4 component ISP...
Sending ISP (9134117 bytes)...
Extracting 018-58213-095.dmg.trustcache (Firmware/018-58213-095.dmg.trustcache)...
Personalizing IMG4 component RestoreTrustCache...
Sending RestoreTrustCache (12398 bytes)...
Extracting DeviceTree.d201ap.im4p (Firmware/all_flash/DeviceTree.d201ap.im4p)...
Personalizing IMG4 component RestoreDeviceTree...
Sending RestoreDeviceTree (41385 bytes)...
Extracting sep-firmware.d201.RELEASE.im4p (Firmware/all_flash/sep-firmware.d201.RELEASE.im4p)...
Personalizing IMG4 component RestoreSEP...
Sending RestoreSEP (1510832 bytes)...
Extracting kernelcache.release.iphone10 (kernelcache.release.iphone10)...
Personalizing IMG4 component RestoreKernelCache...
Sending RestoreKernelCache (15705977 bytes)...
getting SEP ticket
Trying to fetch new SHSH blob
Sending TSS request attempt 1... response successfully received
Received SHSH blobs
About to restore device... 
Connecting now...
Connected to com.apple.mobile.restored, version 15
Device ffffffffffffffffffffffffffffffff00000001 has successfully entered restore mode
Hardware Information:
BoardID: 10
ChipID: 32789
UniqueChipID: 5643355510992814
ProductionMode: true
Starting FDR listener thread
Checkpoint 1621 complete with code 0
Checkpoint 1540 complete with code 0
Checkpoint 1679 complete with code 0
Checkpoint 1544 complete with code 0
About to send RootTicket...
Sending RootTicket now...
Done sending RootTicket
Checkpoint 1547 complete with code 0
Waiting for NAND (28)
Checkpoint 1549 complete with code 0
Updating NAND Firmware (58)
Checkpoint 1550 complete with code 0
Checkpoint 1551 complete with code 0
Checkpoint 1628 complete with code 0
Checkpoint 1552 complete with code 0
Checkpoint 1555 complete with code 0
Checkpoint 1662 complete with code 0
About to send NORData...
Found firmware path Firmware/all_flash
Getting firmware manifest from build identity
Extracting LLB.d20.RELEASE.im4p (Firmware/all_flash/LLB.d20.RELEASE.im4p)...
Personalizing IMG4 component LLB...
Extracting applelogo@2x~iphone.im4p (Firmware/all_flash/applelogo@2x~iphone.im4p)...
Personalizing IMG4 component AppleLogo...
Extracting batterycharging0@2x~iphone.im4p (Firmware/all_flash/batterycharging0@2x~iphone.im4p)...
Personalizing IMG4 component BatteryCharging0...
Extracting batterycharging1@2x~iphone.im4p (Firmware/all_flash/batterycharging1@2x~iphone.im4p)...
Personalizing IMG4 component BatteryCharging1...
Extracting batteryfull@2x~iphone.im4p (Firmware/all_flash/batteryfull@2x~iphone.im4p)...
Personalizing IMG4 component BatteryFull...
Extracting batterylow0@2x~iphone.im4p (Firmware/all_flash/batterylow0@2x~iphone.im4p)...
Personalizing IMG4 component BatteryLow0...
Extracting batterylow1@2x~iphone.im4p (Firmware/all_flash/batterylow1@2x~iphone.im4p)...
Personalizing IMG4 component BatteryLow1...
Extracting glyphplugin@1334~iphone-lightning.im4p (Firmware/all_flash/glyphplugin@1334~iphone-lightning.im4p)...
Personalizing IMG4 component BatteryPlugin...
Extracting DeviceTree.d201ap.im4p (Firmware/all_flash/DeviceTree.d201ap.im4p)...
Personalizing IMG4 component DeviceTree...
Extracting liquiddetect@1334~iphone-lightning.im4p (Firmware/all_flash/liquiddetect@1334~iphone-lightning.im4p)...
Personalizing IMG4 component Liquid...
Extracting recoverymode@1334~iphone-lightning.im4p (Firmware/all_flash/recoverymode@1334~iphone-lightning.im4p)...
Personalizing IMG4 component RecoveryMode...
Extracting iBoot.d20.RELEASE.im4p (Firmware/all_flash/iBoot.d20.RELEASE.im4p)...
Personalizing IMG4 component iBoot...
Personalizing IMG4 component RestoreSEP...
Personalizing IMG4 component SEP...
Sending NORData now...
Done sending NORData
ERROR: Unable to receive message from FDR 0x19d8ab0 (-2). 0/2 bytes`

**Comment by Cryptiiiic** [comment]
add -j

**Comment by masckmaster2007** [comment]
It worked ! What is the -j arg btw ?

**Comment by Cryptiiiic** [comment]
its in the usage
