### ISSUE TITLE
iPhone XS Max stucked on recovery mode after upgrading to 15.1

### ISSUE THREAD

**Issue by Alharthi6** [marijuanARM/futurerestore#129]
I’ve stucked at recovery mode after futurerestore upgrading to 15.1, what could I do now? I’ve successfully upgraded to 14.7.1 but I faced same issues on 14.2 so decided to go to 15.1 . I’ve got at the end of up gray for both 14.2 to 14.7.1 and 14.7.1 to 15.1 same message: Unable to restore device. But for 15.1, got stuck forever… Clicking exit recovery on both Futurerestore and 3utools doesn’t help, iPhone reboots and goes back to recovery staying forever… I’ve tried to Futurerestore again for same 15.1 but got: Device ApNonce does not match APTicket nonce. I’ve copied the logs to work file.

**Comment by HydrationMan** [comment]
The logs in question would be delightful :trollface:

**Comment by Alharthi6** [comment]
Its very huge, should i upload it full?
Ive uploaded it below..

**Comment by Alharthi6** [comment]
here it is in word file
[fr.docx](https://github.com/futurerestore/futurerestore/files/10216327/fr.docx)

**Comment by Cryptiiiic** [comment]
You did something extremely stupid.
1. you used 300 when latest is 302 which is always a bad idea, using outdated software
2. you restored using iOS 16 sep??? why would you do that, obviously it will brick.
`C:\Users\m\Downloads\15.1\futurerestore_300_local_win_x64.exe --apticket
C:\Users\m\Downloads\15.1\XXXX_iPhone11,6_d331pap_15.1-
19B74_ec6245b3b9b91a51ccef556a7602aaaa8456568e0a2ecbd369dedd85dc371c45.shsh2 --debug --
update --no-rsep --custom-latest 16.1.2 --latest-sep --latest-baseband
C:\Users\m\Downloads\15.1\iPhone11,2,iPhone11,4,iPhone11,6,iPhone12,3,iPhone12,5_15.1_19B74_R
estore.ipsw`

restore to latest and do more research next time(if there's even a next time)

**Comment by Alharthi6** [comment]
It doesn’t accept to restore to 15.7 
Tried both builds 19H12 and 19G71 
Did you read my post?!

**Comment by Alharthi6** [comment]
For windows it only showed me 300 build of futurerestore not 302!

**Comment by HydrationMan** [comment]
It not accepting 15.7 (which is unsigned) doesn't mean you use iOS 16 components.

**Comment by HydrationMan** [comment]
15.6RC(19G69) is what you should have used

**Comment by Alharthi6** [comment]
So tell me which one I must use

**Comment by Cryptiiiic** [comment]
Obviously it only works for versions that are being signed. So 16.1.2 was signed so that worked. But why would you use that?
16 SEP is incompat with 15.x
15.7.x is unsigned, 15.6 RC was the one you should have used 19G69 like hydrate said

**Comment by Alharthi6** [comment]
Mmmm, so now no option to restore whatever version of my saved bolbs?

**Comment by HydrationMan** [comment]
Yeah. Since the restore cocked up now your nonce is no longer set as it has been consumed.

**Comment by Cryptiiiic** [comment]
why would I tell you to restore to latest if there was an option to use the blobs?
clearly there is no option by me telling you to restore to latest...

**Comment by Alharthi6** [comment]
Ok, but I used 19G71 for my first upgrade but couldn’t on second one, that’s why kept trying and searching then found telegram bot for sep and it’s suggested me to just choose this firmware

**Comment by Cryptiiiic** [comment]
that's really stupid

**Comment by Alharthi6** [comment]
I never used 19G69
I kept search for 5 days then started by upgrading 14.2 to 14.7.1 using 19G71
Then day later from 14.7.1 to 15.1 tried same build but couldn’t then went all 15 builds here in picture
![Uploading image.jpg…]()

**Comment by Alharthi6** [comment]
And for futureresttore build it gave me same 300 right now !
![Uploading image.jpg…]()

**Comment by Alharthi6** [comment]
Anyway, thanks for your so kindness

**Comment by Alharthi6** [comment]
I just wanna let you know guys for anyone faced similar case, I just updated normally to latest 16.1.2 then two days later daowngraded to 15.6 RC (19G69) through iTunes
