### ISSUE TITLE
A10 15.4 to 14.4 Stuck at No data to Read

### ISSUE THREAD

**Issue by L1keava** [marijuanARM/futurerestore#132]
**I want to downgrade my iPhone7 to iOS14.4. It is now iOS15.4.
 I have blob file (With Generator). But I'm running into a problem.
In fact, I tried it once half a year ago. It is also stuck in the no data to read loop. 
At this time, my phone should be in recovery mode. In addition, after my phone restarts and enters normal mode, my software data is all there, and nothing has changed. 
So I checked the information and I used --no-rsep. It didn't help. The problem is the same as before. 
By the way my iPhone didn't get a green screen or any other colored screen during this restore. (Maybe this helps in diagnosing the issue?) 
I've also worked around this issue before, but I don't have logs, I'll try to reproduce it if needed. At that moment my iPhone shows the Apple logo and a progress bar. But the progress of the progress bar is almost 0. It still hasn't changed after restarting my phone
Here is my log, hope someone can help me, thank you. If you need any other information about my problem, I will add it. thanks.**
Links to my full logs:https://drive.google.com/file/d/1hIERMw50jrOT6M_mivLAo85HkfknsdHw/view?usp=share_link
![WX20230103-142616](https://user-images.githubusercontent.com/111690660/210308969-1afe9cfd-29da-41d3-b736-438e4a9830a4.png)

**Comment by Cryptiiiic** [comment]
@L1keava try 19G69 also try with and without rsep option

**Comment by L1keava** [comment]
> @L1keava try 19G69 also try with and without rsep option


Thanks for your help. Do you mean --custom-latest-buildid "19G69" ?
I tried but it didn't help. The green screen shows up then stuck at no data to read,then my phone reboot to recovery mode again.
This is the way I tried. am i wrong?
![WX20230103-155608](https://user-images.githubusercontent.com/111690660/210318227-c7e5bbfc-ae71-4172-ab22-ae83fc952073.png)

**Comment by ghost** [comment]
Same issue on A11 But trying to downgrade from 15.6 to 14.2

**Comment by Cryptiiiic** [comment]
everyone knows you can't

**Comment by L1keava** [comment]
> 

Someone replied to me on Discord.  He solved the problem by upgrading his iPhone to iOS 15.7 . I think the problem is that the iPhone needs a clean flash. Can you try? And have you tried no-rsep ?

**Comment by L1keava** [comment]
> Same issue on A11 But trying to downgrade from 15.6 to 14.2

Someone replied to me on Discord. He solved the problem by upgrading his iPhone to iOS 15.7 . I think the problem is that the iPhone needs a clean flash. Can you try? And have you tried no-rsep ?

**Comment by L1keava** [comment]
> everyone knows you can't

Sorry about that, I will close this issues. Thanks.
