### ISSUE TITLE
Bug: incompatible with the seemingly inconsistent naming for the iPhone8 Plus

### ISSUE THREAD

**Issue by ZOrangeBandit** [marijuanARM/futurerestore#133]
The naming convention seems for the iPhone 8 Plus seems to be inconsistent, falling under the names "iPhone10,5" and "iPhone5.5" which seems to cause the following error.
`[Error] [TSSC] device 'iPhone10,5' could not be found in devicelist`
`futurerestore: failed with exception:`
`[exception]:`
`what=Could not find url of latest firmware version`
Full run log: https://pastebin.com/uUcWn0x4

**Comment by Cryptiiiic** [comment]
bruh, custom latest implies a signed firmware not 14.2.... @ZOrangeBandit
