### ISSUE TITLE
Problem on windows FutureRestore Executable 

### ISSUE THREAD

**Issue by sasa113** [marijuanARM/futurerestore#134]
Hey i have an error message when i want to install the FutureRestore executable the error message is : No FutureRestore beta asset found for your operating system. Try a release version instead, or manually download a beta for your OS. https://github.com/futurerestore/futurerestore/actions .
(i am under windows 10)
thanks

**Comment by Cryptiiiic** [comment]
https://cdn.cryptiiiic.com/bin/Windows/x86_64/futurerestore/
