### ISSUE TITLE
Error : Could not find url of latest firmware version

### ISSUE THREAD

**Issue by sasa113** [marijuanARM/futurerestore#135]
[10] Make sure to hit "trust" on your device if prompted!
FutureRestore GUI Log – 2023-02-06T12.37.50.982678200
Command ran: C:\Users\Moi\Downloads\futurerestore-Windows-x86_64-v2.0.0-test-Build_304-RELEASE (1).exe --apticket C:\Users\Moi\Documents\1526234249035822_iPhone11,8_n841ap_16.3-20D47_f75df834e1b6248d12c48f6fa0873c2b2ee74f00f9c74e02f9b4550e48d54d6f.shsh2 --debug --latest-sep --latest-baseband C:\Users\Moi\Downloads\iPhone11,8_16.2_20C65_Restore.ipsw 
Version: v2.0.0-test(ca45da2fb075ccf2921bbc04d5aef74e3e71b743-304)
img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f-RELEASE
libipatcher version: 0.88-1e855d70c84419014e363bdbcaead7b145fe3e1f-RELEASE
Odysseus for 32-bit support: yes
Odysseus for 64-bit support: yes
[INFO] 64-bit device detected
futurerestore init done
reading signing ticket C:\Users\Moi\Documents\1526234249035822_iPhone11,8_n841ap_16.3-20D47_f75df834e1b6248d12c48f6fa0873c2b2ee74f00f9c74e02f9b4550e48d54d6f.shsh2 is done
User specified to use latest signed SEP
[TSSC] opening firmwares.json
[DOWN] downloading file https://api.ipsw.me/v2.1/firmwares.json/condensed
[TSSC] selecting latest firmware version: 16.3
[Error] [TSSC] device 'iPhone11,8' could not be found in devicelist
futurerestore: failed with exception:
[exception]:
what=Could not find url of latest firmware version

code=117506100
line=1793
file=C:/Users/Cryptic/futurerestore/src/futurerestore.cpp
commit count=304:
commit sha  =ca45da2fb075ccf2921bbc04d5aef74e3e71b743:
FutureRestore process ended.

**Comment by Cryptiiiic** [comment]
This means your internet can't download https://api.ipsw.me/v2.1/firmwares.json/condensed
or it failed to download the entire file. See if you can download it in browser.

**Comment by sasa113** [comment]
ok its works i can download it but what next ?

**Comment by Cryptiiiic** [comment]
how big is the file downloaded in browser though?

**Comment by Cryptiiiic** [comment]
you still there?
