### ISSUE TITLE
my blob file is bshsh2 file, what can i do?

### ISSUE THREAD

**Issue by chenfanfang** [marijuanARM/futurerestore#141]
<img width="795" alt="image" src="https://github.com/futurerestore/futurerestore/assets/13808962/ae212556-e865-404f-8d75-ada401730321">

I do not know why my blob file is bshsh2 file. Everyone is a shsh2 file。

help me please

thanks

**Comment by Cryptiiiic** [comment]
Just binary plist, shouldn’t affect anything, conan enabled it for space reasons

**Comment by chenfanfang** [comment]
> 

thanks
