### ISSUE TITLE
[Bug] Windows futurerestore fails with "Could not find url of latest firmware version"

### ISSUE THREAD

**Issue by kabegithub** [marijuanARM/futurerestore#145]
`Version: v2.0.0-test(ca45da2fb075ccf2921bbc04d5aef74e3e71b743-304)
img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f-RELEASE
libipatcher version: 0.88-1e855d70c84419014e363bdbcaead7b145fe3e1f-RELEASE
Odysseus for 32-bit support: yes
Odysseus for 64-bit support: yes
[INFO] 64-bit device detected
futurerestore init done
reading signing ticket D:\My Profiles\Downloads\Compressed\SHSH_Blobs.tar\SHSH Blobs\15.6 [[RC]]\19G69\no-apnonce\660609089699878_iPhone9,1_d10ap_15.6-19G69_27325c8258be46e69.shsh is done
User specified to use latest signed SEP
[TSSC] opening firmwares.json
[DOWN] downloading file https://api.ipsw.me/v2.1/firmwares.json/condensed
[TSSC] selecting latest firmware version: 15.7.7
[Error] [TSSC] device 'iPhone9,1' could not be found in devicelist
futurerestore: failed with exception:
[exception]:
what=Could not find url of latest firmware version
`

I can download [condensed.json](https://api.ipsw.me/v2.1/firmwares.json/condensed) with 3.67MB

**Comment by Cryptiiiic** [comment]
Just try again, also send full command, also better help on the discord.

**Comment by autumnot** [comment]
I used pwndfu, same problem

[TSSC] opening firmwares.json
[DOWN] downloading file https://api.ipsw.me/v2.1/firmwares.json/condensed
[TSSC] selecting latest firmware version: 16.5.1
[Error] [TSSC] device 'iPhone10,4' could not be found in devicelist
futurerestore: failed with exception:
[exception]:
what=Could not find url of latest firmware version

code=117506100
line=1793
file=C:/Users/Cryptic/futurerestore/src/futurerestore.cpp
commit count=304:
commit sha  =ca45da2fb075ccf2921bbc04d5aef74e3e71b743:
FutureRestore process ended.

**Comment by kabegithub** [comment]
Do you notice my post on discord？ https://discord.com/channels/842189018523631658/1121715636922495096

**Comment by brightback12** [comment]
I have SEP already, it won't let me use it. It keeps throwing error "--sep is Deprecated! Please switch to --custom-latest or --custom-latest-beta". even after setting custom version.
I feel its a bug in the code

**Comment by Cryptiiiic** [comment]
because you aren't supposed to use it, whats so hard to understand

**Comment by brightback12** [comment]
even when I select no SEP, it doesn't work. I don't mean to argue. Moreover do you know any way to downgrade from 15.1 to 14.8(A10X)

**Comment by Cryptiiiic** [comment]
Good news, "Could not find url of latest firmware version" is fixed in 321
