### ISSUE TITLE
SLF4J error on windows 10/11 as well as Ubuntu 22.0.4

### ISSUE THREAD

**Issue by ysmalik09** [marijuanARM/futurerestore#146]
Hi,
I'm getting following same error on Windows 10 as well as Linux;
**SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger **implementation**
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.**
Updated java to jre-8u371 (latest), uninstall and reinstall all Apple software's and drivers. 
Please help, Thanks

**Comment by Cryptiiiic** [comment]
Wrong repo? Fr isn’t java are you tryin true gui wrapper?

**Comment by ysmalik09** [comment]
Thanks for your quick response. I'm using FutureRestore-GUI-Windows-1.98.3.msi  and trying to downgrade from ios 16.5.1 to 16.5 with blob

**Comment by Cryptiiiic** [comment]
Fr gui wraps this tool, that’s a gui issue so you should probably ask on that repo or on the discord
