### ISSUE TITLE
iPhone 7 not supported by Apple anymore (bricked Upgrades/Downgrades via futurerestore using saved shsh2 blobs)

### ISSUE THREAD

**Issue by joeyoropesa-dev** [marijuanARM/futurerestore#149]
I've tried everything. I just wanted to upgrade from iOS 14.3 to unsigned iOS 15.6b3 or some vulnerable version to support CoreTrust bug but nothing works.

The Apple server doesn't support my device model anymore and when I tried to specify the SEP firmware for the latest supported still signed iOS ipsw (extracted), it said that -s and -b command are depreciated so I was forced to use --custom-latest-build or --custom-latest-beta but I don't know how can I use it

Anyway, I've tried to do something replacing -s and -b %path% with --custom-latest-build %path% and --custom-latest-beta %path% but that didn't worked too. Instead the verification was bypassed but it doesn't started flashing - instead it just stopped.

What's wrong and how this "EOL status by Apple servers for iPhone 7 models" can be fixed/bypassed successfully to use saved shsh2 blobs to upgrade/downgrade

**Comment by joeyoropesa-dev** [comment]
Connected with the case #145

**Comment by Cryptiiiic** [comment]
@admin-elvistrujanovic how's this connected to issue 145?

**Comment by joeyoropesa-dev** [comment]
> @admin-elvistrujanovic how's this connected to issue 145?

Well I've had the same issue and how you said earlier [https://github.com/futurerestore/futurerestore/issues/145#issuecomment-2128727201](https://github.com/futurerestore/futurerestore/issues/145#issuecomment-2128727201), it's fixed. 👍
