### ISSUE TITLE
don't redirect pacman errors into /dev/null

### ISSUE THREAD

**Issue by dipshit-enterprises** [marijuanARM/futurerestore#160]
The `linux_fix.sh` uses the `-Syy` and then `-S` pacman flags for installing the required packages. This is dangerous, but I understand that people might also not want to update their entire system without confirmation. 

As a compromise, I ask that you please at the very least don't redirect errors for these commands into `/dev/null`. Pacman logs can contain important information about problems that may render the system un-bootable. 

I can't make a commit/pr since the script is on a cdn, but my proposed fix is to change:
```bash
sudo pacman -Syy --needed --noconfirm >/dev/null 2>/dev/null
sudo pacman -S --needed --noconfirm udev usbmuxd >/dev/null 2>/dev/null
```
to:
```bash
sudo pacman -Syy --needed --noconfirm >/dev/null
sudo pacman -S --needed --noconfirm udev usbmuxd >/dev/null
```
or even just get rid of `/dev/null` entirely, and let the user approve of the operations:
```
sudo pacman -Syy --needed
sudo pacman -S --needed udev usbmuxd
```

This would have saved me the trouble of fixing my init system after running the script and being unable to boot, as I later remembered seeing this in the script and discovered the errors present in `/var/log/pacman.log`.

**Comment by Cryptiiiic** [comment]
done

**Comment by dipshit-enterprises** [comment]
thanks
