### ISSUE TITLE
Can flash the specified rootfs dmg with the latest firmware?

### ISSUE THREAD

**Issue by luobo180180** [marijuanARM/futurerestore#44]
A：Can flash the specified rootfs dmg with the latest firmware?
B：To flash a custom rootfs you need to have a checkm8 or 32bit device. And it will be tethered on and above 14.2.

A：You can use APTicket and APNonce to flash into the specified rootfs dmg through futurerestore.
Then why can't I use the latest firmware as the carrier to flash the specified rootfs dmg?

**Comment by Cryptiiiic** [comment]
Please provide a better translation this is unintelligible.

**Comment by Cryptiiiic** [comment]
To flash a custom rootfs you need to have a checkm8 or 32bit device. And it will be tethered on and above 14.2.
