### ISSUE TITLE
IBSS ERROR

### ISSUE THREAD

**Issue by AdamBurchart** [marijuanARM/futurerestore#47]
After setting nonce with Checkm8 nonce seter in futurerestore beta 2.0 I have error Device did not reconnect. Possibly invalid IBSS. Restart device and try again.
I'm using Mac OS mojave hackintosh
![144751817-6624909e-ae3f-4d07-bd16-99e8515f476e](https://user-images.githubusercontent.com/95493447/144894821-dd4dd1d9-7945-41da-bb9f-47ed9113c7de.jpg)
h

**Comment by Cryptiiiic** [comment]
You do realize you have to pwn bootrom then patch bootrom signature checks right?

**Comment by TheAwesomeGuy11** [comment]
@Cryptiiiic I'm experiencing this too. I have pwned the bootrom as well
