### ISSUE TITLE
SEP not signed even using latest SEP

### ISSUE THREAD

**Issue by peter17ji** [marijuanARM/futurerestore#48]
futurerestore v194.
https://pastebin.com/UGtGLrGk

**Comment by peter17ji** [comment]
"C:\p\futurerestore-v194.exe" --apticket "C:\Users\peter\Downloads\MY_ECID_HERE_iPhone11,8_n841ap_14.5.1-18E212_MY_NONC_HERE.shsh2" --debug --update --latest-sep --latest-baseband "C:\Users\peter\Downloads\iPhone11,8,iPhone12,1_14.5.1_18E212_Restore.ipsw"

**Comment by Cryptiiiic** [comment]
v194 is obsolete use Linux or Mac with beta
