### ISSUE TITLE
Error while downgrading from iOS 15 to 14.5

### ISSUE THREAD

**Issue by TheAwesomeGuy11** [marijuanARM/futurerestore#50]
`Variant: Customer Erase Install (IPSW)
This restore will erase your device data.
irecv_event_cb: device 001869dc0006002e (udid: N/A) connected in DFU mode
Device found in DFU Mode.
Getting firmware keys for: d20ap
irecv_event_cb: device 001869dc0006002e (udid: N/A) disconnected
Repacking patched bootloaders as IMG4
Cleaning up...
[exception]:
what=Device did not reconnect. Possibly invalid iBSS. Reset device and try again
code=40960017
line=625
file=futurerestore.cpp
commit count=268:
commit sha  =b013fff1e54f896fd2fb2834ea02615ee99314d8:
Done: restoring failed!
`

Any idea what is causing this and how to fix it?

**Comment by Cryptiiiic** [comment]
Redownload 264. Build 268 is a phantom build don't use it :trol:

**Comment by TheAwesomeGuy11** [comment]
> Redownload 264. Build 268 is a phantom build don't use it :trol:

wdym redownload  264, i’m pretty sure i’m using v2.0.0 beta

**Comment by HydrationMan** [comment]
Says right there that you’re using 268 at the bottom of your log
