### ISSUE TITLE
Unable to downgrade when device current iOS is 15.3

### ISSUE THREAD

**Issue by teelekkung** [marijuanARM/futurerestore#51]
Part of output from 198

sending nordata now... done 
sending nordata 
unmounting filesystems (29) 
unmounting filesystems (29) 
unmounting filesystems (29) 
unmounting filesystems (29)
unmounting filesystems (29) 
unmounting filesystems (29) 
about to send fdr trust data... 
sending fdr trust data now... done 
sending fdr trust data checking for uncollected logs (44) 
checking for uncollected logs (44) 
error: unable to receive message from fdr 0x600001c582e0 (-2). 0/2 bytes 
error: could not read data (-256). aborting. 
cleaning up... 
[exception]: what=error: unable to restore device

Part of output from 265

checkpoint 1558 complete with code 0 
checkpoint 1559 complete with code 0 
checkpoint 1560 complete with code 0 
checking for uncollected logs (44) 
checkpoint 1561 complete with code 0 
checking for uncollected logs (44) 
cleaning up... 
[exception]: what=error: unable to restore device

I already deleted full log so I have to remaking problem after reinstall iOS
Device I used 
iPhoneSE1 n69ap
MBA late 2018 Monterey 12.2 21D49 (also happened in 12.3 beta)

I used [a9-checkm8-nonce-setter-script](https://github.com/rA9stuff/a9-checkm8-nonce-setter-script) to set nonce
[Here is futurerestore198 output when used on same device but iOS 15.2.1 installed](https://github.com/m1stadev/futurerestore/files/7964689/success15.2.1.to.14.3.txt)

**Comment by teelekkung** [comment]
Seem to be fix??? idk , when I can reproduce problems I will reopen this issue

**Comment by teelekkung** [comment]
Too soon to be close , I finally make it 
[198unsuccess15.3 to 14.3.txt](https://github.com/m1stadev/futurerestore/files/7964809/198unsuccess15.3.to.14.3.txt)

**Comment by teelekkung** [comment]
Too soon to be close , I finally make it 
[198unsuccess15.3 to 14.3.txt](https://github.com/m1stadev/futurerestore/files/7964809/198unsuccess15.3.to.14.3.txt)

**Comment by Cryptiiiic** [comment]
@teelekkung you using outdated futurerestore. Please use 265 linked in the actions tab. Or on nightly.link.
Also why would use being using that noncesetter script when set nonce is built into futurerestore, the only prerequisite is running eclipsa for your SE first to patch DFU mode sigchecks. Then you can read the futurerestore usage/help for the binary.

**Comment by teelekkung** [comment]
I able to reproduce problem  with 198 but not 256, Before they were broke  but now they work , that why I didn't attach log of 265  and why I still use noncesetter.    Still WIP to reproduce the  problem . if you click to see my issue edit I also mentioned that they also happened but decide to delete the mention because I put a part that I googled in

**Comment by Cryptiiiic** [comment]
198 is out of production, obsolete, discontinued why would you bother reproducing for it wtf. Thats like showing an iOS 12 bug to an apple dev when iOS 15 is in production. It been long improved upon and fix this is a dev nightmare when you do this kinda testing and try to use the issues tab in this way.
