### ISSUE TITLE
Unknown data request 'FirmwareUpdaterPreflight' received

### ISSUE THREAD

**Issue by SpaceMember** [marijuanARM/futurerestore#52]
15.3 -> 15.2 SE1. What's wrong? No further downgrade. futurerestore v194 for Windows

**Comment by SpaceMember** [comment]
![xcpvxcpvxcxc](https://user-images.githubusercontent.com/60446457/151683178-436890f2-71ee-4eef-8dc1-13b68dad662c.png)

**Comment by verygenericname** [comment]
you need linux/macos use the latest build

**Comment by verygenericname** [comment]
in Actions

**Comment by Cryptiiiic** [comment]
@SpaceMember I've not yet made a new windows version please use 265 on mac or linux or wait for windows version sorry.
