### ISSUE TITLE
Broke downgrade to iOS 14

### ISSUE THREAD

**Issue by SpaceMember** [marijuanARM/futurerestore#59]
The latest beta futurestore broke downgrade 6s from ios 15 to 14. The previous beta restores successfully. Recovery log ios 14.3 from 15.4:
[15.4 to 14.3 FR log.txt](https://github.com/m1stadev/futurerestore/files/8215572/15.4.to.14.3.FR.log.txt)

**Comment by Haeckli** [comment]
I can confirm the exact same error on my iPhone 7. Since a couple of days I was trying to understand why its failing. This issue finally pointed to the right thing. 
Each run of the current version 267 is stopped with a "**Segmentation fault (core dumped)**" message right after "**Received Baseband SHSH blobs**". I guess this indicates a crash of the program. A few seconds later the phone reboots into recovery mode. This error repeats 100%. 

I attach 2 console outputs: 
- [1 - FutureRestore267 - iPhone 7 - 14.3 to 14.3.txt](https://github.com/m1stadev/futurerestore/files/8216802/1.-.FutureRestore267.-.iPhone.7.-.14.3.to.14.3.txt)
This was created with version 267. 
It does not contain any uncollected logs, indicating that the previous restore was OK. 
But at the end it shows the crash. 
- [2 - FutureRestore266 - iPhone 7 - 14.3 to 14.3.txt](https://github.com/m1stadev/futurerestore/files/8216807/2.-.FutureRestore266.-.iPhone.7.-.14.3.to.14.3.txt)
This was created with version 266 right after the previous crash
It contains the uncollected log from the phone of the crashed 267 run which seems to be a precise copy of the log posted by @SpaceMember 
This run completes without any error and the phone reboots into the normal mode as expected. 

Any idea? I can do more testing if required...

**Comment by HydrationMan** [comment]
Use the debug build and try capture the crash

**Comment by Haeckli** [comment]
> Use the debug build and try capture the crash

I have a debugger installed (GDB) but honestly I'm not really skilled in using it. Have me some advice?

**Comment by Cryptiiiic** [comment]
you don't use it, you send the crashlog from the DEBUG build, it has symbols.

**Comment by Haeckli** [comment]
> you don't use it, you send the crashlog from the DEBUG build, it has symbols.

OK, give me a few minutes. Where will I find that crashlog?

**Comment by Cryptiiiic** [comment]
I don't really use linux, I assume /var/log/messages?

**Comment by Haeckli** [comment]
> I don't really use linux, I assume /var/log/messages?

Having some trouble - be patient...

**Comment by Haeckli** [comment]
OK, finally I made it after taking a 4 hour crash-course on the creation of crash-dumps on Ubuntu systems... ;-) 
Here are the results: 

- [3 - FutureRestore267 - iPhone 7 - 14.3 to 14.3.txt](https://github.com/m1stadev/futurerestore/files/8218943/3.-.FutureRestore267.-.iPhone.7.-.14.3.to.14.3.txt)
This is the console output of the FutureRestore267(debug) run. 
(like in my [previous post)](https://github.com/m1stadev/futurerestore/issues/59#issuecomment-1063190984)
- [_home_kpeiffer_Desktop_FutureRestore_futurerestore267debug.1000.zip](https://github.com/m1stadev/futurerestore/files/8218945/_home_kpeiffer_Desktop_FutureRestore_futurerestore267debug.1000.zip)
This (hopefully) is the Core-Dump created when FutureRestore267 crashed... 

I hope this is what you are looking for... 
Let me know if I can give any additional support.

**Comment by Cryptiiiic** [comment]
can you zip /tmp/futurerestore and send it here

**Comment by Cryptiiiic** [comment]
wait a second, why are you manually specifying baseband and sep? thats probably why its crashing baseband or manifest is corrupt

**Comment by HydrationMan** [comment]
ive seen A L O T of people thinking 15.4RC being out means its "latest"

**Comment by Cryptiiiic** [comment]
...

**Comment by Haeckli** [comment]
> can you zip /tmp/futurerestore and send it here

This is empty...

**Comment by Cryptiiiic** [comment]
@Haeckli read the second comment it was a nevermind be cause you manually specified

**Comment by Haeckli** [comment]
> wait a second, why are you manually specifying baseband and sep? thats probably why its crashing baseband or manifest is corrupt

I do because its faster in typing than alway typing --latest-sep and --latest-baseband. 
But I can try running with ---latest...

**Comment by Cryptiiiic** [comment]
did you check if the baseband was an actual valid file? or was it only partially downloaded, or empty even

**Comment by Haeckli** [comment]
> did you check if the baseband was an actual valid file? or was it only partially downloaded, or empty even

These are the same SEP & BaseBand & Buildmanifests that work perfectly with either the release version 194 or the bets 266...

**Comment by Cryptiiiic** [comment]
If it still breaks with latest flags then its an issue otherwise Im not sure

**Comment by Haeckli** [comment]
> If it still breaks with latest flags then its an issue otherwise Im not sure

I will try... 
The SEP & Baseband & Buildmanifests were extracted directly from the IPSW and not downloaded elsewhere...

**Comment by Haeckli** [comment]
Believe it or not: with the **--latest** options even version 267 finishes the restore without errors.
Now, as I used the **--latest** option, the downloaded files are in the /tmp/futurerestore folder.  
Here ist the zip-file of those: [tmp_futurerestore.zip](https://github.com/m1stadev/futurerestore/files/8219222/tmp_futurerestore.zip)

Tomorrow I need to understand the difference between these downloaded files and those that I extracted from the IPSW file. 
Also I will test if the successful restore repeats... 

Very strange...

**Comment by Haeckli** [comment]
I tested 3 times now with **--latest** and always **NO errors**. 
The downloaded files in /tmp/futurerestore are in a binary compare precisely the same as those I extracted from the IPSW and provided via command-line. So the crash-problem must be connected to how the files are handled when either downloaded or provided via command-line...

**Comment by Cryptiiiic** [comment]
@Haeckli I found the problem and will fix it soon

**Comment by Haeckli** [comment]
> @Haeckli I found the problem and will fix it soon

**COOL ;))**

**Comment by Haeckli** [comment]
So I go sleeping now... It's 2:15 am here...

**Comment by Cryptiiiic** [comment]
<img width="1330" alt="image" src="https://user-images.githubusercontent.com/27748705/157622057-501be22a-b2b3-4eb3-a063-ffe3bba1cde6.png">
<img width="359" alt="image" src="https://user-images.githubusercontent.com/27748705/157622605-da8fc7ae-ab34-4003-9a53-2bb0bf2607fa.png">
push update soon

**Comment by Haeckli** [comment]
> <img alt="image" width="1330" src="https://user-images.githubusercontent.com/27748705/157622057-501be22a-b2b3-4eb3-a063-ffe3bba1cde6.png">
> 
> push update soon

Ah, I see... It was the naming of my input-files - I already thought about this after all the testing... 
I will give it a try once it's available.

**Comment by Cryptiiiic** [comment]
manually specifying was broken, I fixed it

**Comment by Haeckli** [comment]
> push update soon

Great! Will give it a try once it's available....

**Comment by Cryptiiiic** [comment]
Fixed in 9fb4d2c
