### ISSUE TITLE
Link for beta build is broken

### ISSUE THREAD

**Issue by phcella** [marijuanARM/futurerestore#62]
Hi,
https://nightly.link/m1stadev/futurerestore/workflows/ci/test is broken
Can you fix it please?

**Comment by Haeckli** [comment]
The repo has moved to **_futurerestore/futurerestore/_** so the link is now: 
[https://nightly.link/futurerestore/futurerestore/workflows/ci/test](url)

**Comment by phcella** [comment]
Thanks!! Just need to update the link on README.md
