### ISSUE TITLE
Bug: random race conditions leading to crashing on multiple os's

### ISSUE THREAD

**Issue by Cryptiiiic** [marijuanARM/futurerestore#64]
Most likely related to usbmuxd subscribe(so the host os is locking the rights and fr accidently tries to locked rights as well leading to crash?) Need DEBUG build crash logs. This doesn't happen all the time but annoying when it does.

Looking for people to use the DEBUG build to get me a crash log.

**Comment by growtopiajaw** [comment]
Here are at least 8 different times I've encountered this scenario on clean install of Ubuntu 20.04.4 LTS amd64 with futurerestore DEBUG build 288.

[LOG6.txt](https://github.com/futurerestore/futurerestore/files/9187917/LOG6.txt)
[LOG7.txt](https://github.com/futurerestore/futurerestore/files/9187918/LOG7.txt)
[LOG8.txt](https://github.com/futurerestore/futurerestore/files/9187920/LOG8.txt)
[LOG1.txt](https://github.com/futurerestore/futurerestore/files/9187921/LOG1.txt)
[LOG2.txt](https://github.com/futurerestore/futurerestore/files/9187923/LOG2.txt)
[LOG3.txt](https://github.com/futurerestore/futurerestore/files/9187926/LOG3.txt)
[LOG4.txt](https://github.com/futurerestore/futurerestore/files/9187927/LOG4.txt)
[LOG5.txt](https://github.com/futurerestore/futurerestore/files/9187928/LOG5.txt)

**Comment by Cryptiiiic** [comment]
asan is better for this purpose

**Comment by Cryptiiiic** [comment]
also you shouldn't be using --rdsk --rkrn they are redundant if you are already using a cfw

**Comment by growtopiajaw** [comment]
I'm using --rdsk and --rkrn for tethered downgrade. I'll try asan and report back

**Comment by Cryptiiiic** [comment]
well you were informed wrong those args are for stock restores with patched restore mode. Your cfw should have patched kernel with krnl tag not rkrn and don't use those flags

**Comment by growtopiajaw** [comment]
The ipsw itself is stock just with patched kernel outside of the ipsw

**Comment by Cryptiiiic** [comment]
I guess thats fine since you are doing stock. Anyway I fixed the crash on mac by finding out which processes were claiming the usb interfering with fr. Idk what that would be on linux. Need crash logs or run asan build with symbolizer. Can also look in dmesg for usb claim errors.

**Comment by mineek** [comment]
Yea he was using sunst0rm iirc, sunst0rm always uses stock ipsw but uses those arguments

**Comment by Cryptiiiic** [comment]
I don't recommend using products by a beginner dev. They don't exactly know what they are doing.

**Comment by mineek** [comment]
Yea ik im very beginner and i know i can also still learn a lot but for now sunst0rm is in a 'usable' state.

**Comment by Cryptiiiic** [comment]
@mineek I'm saying this because I came from there I know what its like. It just takes time and support from others.

**Comment by mineek** [comment]
Alright, but not too get to off-topic, this issue is not present on my 6s ( both on my amd laptop and my intel pc - ubuntu 20.04 LTS ) as far as i've tested.

**Comment by Cryptiiiic** [comment]
@mineek hence the issue title "random" :)

**Comment by mineek** [comment]
yeah i see, but i restored it over like 20 times now and it hasnt occured but maybe its my enviroment or smth

**Comment by Cryptiiiic** [comment]
It's a race condition we just need to find what triggers it.

**Comment by growtopiajaw** [comment]
I got some asan crash logs on my Monterey Hackintosh. `libclang_rt.asan_osx_dynamic.dylib` was copied from `/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/lib/darwin` and I exported `ASAN_SYMBOLIZER_PATH="$(which llvm-symbolizer)"`. `llvm-symbolizer` is installed through procursus `llvm-utils`

The last one is a successful restore but I'm not sure if it's a crash, though I'll admit the asan build requires far less tries than the release and debug builds.
[LOG1.TXT](https://github.com/futurerestore/futurerestore/files/9189219/LOG1.TXT)
[LOG2.TXT](https://github.com/futurerestore/futurerestore/files/9189225/LOG2.TXT)
[LOG3.TXT](https://github.com/futurerestore/futurerestore/files/9189226/LOG3.TXT)
[LOG4.TXT](https://github.com/futurerestore/futurerestore/files/9189228/LOG4.TXT)

**Comment by Cryptiiiic** [comment]
The first crashes it looks like asan itself crashed rendering the log useless but the last one is a bug I’ve seen before but not sure how to fix. You can check the Syslog and filter by appleusbhost.
