### ISSUE TITLE
Failed to restore devices from iOS 15.4 to iOS 14.6

### ISSUE THREAD

**Issue by samleong123** [marijuanARM/futurerestore#71]
Unable to restore devices from iOS 15.4 to iOS 14.6
Using pwndfu mode with set nonced
iPhone 6s , N71AP 
Logs attached :
[FRLog_2022-04-01T12.09.55.932632.txt](https://github.com/futurerestore/futurerestore/files/8394645/FRLog_2022-04-01T12.09.55.932632.txt)
[FRLog_2022-04-01T12.10.42.034181.txt](https://github.com/futurerestore/futurerestore/files/8394646/FRLog_2022-04-01T12.10.42.034181.txt)

**Comment by Cryptiiiic** [comment]
@samleong123 can you get me a log with CLI instead of GUI?

**Comment by samleong123** [comment]
> @samleong123 can you get me a log with CLI instead of GUI?
![Screenshot 2022-04-01 at 12 25 12 PM](https://user-images.githubusercontent.com/58818070/161194891-694ac6a1-14c5-410e-ac19-4ed1cbe76643.png)

the GUI logs should contains CLI logs i think?
Because the logs i saw on GUI is also the same
just it's contains some GUI command but CLI logs are also there

**Comment by Cryptiiiic** [comment]
Its run via gui so its still a gui log. The gui is known for messing with the log at times. You need to run fr in terminal for an actual cli log not the gui hence the name cli...

**Comment by Cryptiiiic** [comment]
by the screenshot it tells me that sep is probably incompatible with 14

**Comment by samleong123** [comment]
> by the screenshot it tells me that sep is probably incompatible with 14

Thanks. I got another SHSH blobs for 15.0.2 , so thats means i can only go back to 15.0.2 if SEP is compatible with 15.0.2 or else no chance going back?
Using latest SEP (15.4)

**Comment by samleong123** [comment]
> > by the screenshot it tells me that sep is probably incompatible with 14
> 
> Thanks. I got another SHSH blobs for 15.0.2 , so thats means i can only go back to 15.0.2 if SEP is compatible with 15.0.2 or else no chance going back? Using latest SEP (15.4)

Hmm
it seems like same for 15.0.2
![Screenshot 2022-04-01 at 12 58 20 PM](https://user-images.githubusercontent.com/58818070/161197689-66a4f4db-0e7f-4d8c-8de1-e4b0c9cedd07.png)

**Comment by samleong123** [comment]
> Its run via gui so its still a gui log. The gui is known for messing with the log at times. You need to run fr in terminal for an actual cli log not the gui hence the name cli...
[futurerestore CLI Log 15.0.2.txt](https://github.com/futurerestore/futurerestore/files/8394841/futurerestore.CLI.Log.15.0.2.txt)

This is the CLI Log for iOS 15.4 - iOS 15.0.2

**Comment by Cryptiiiic** [comment]
you don't need to set nonce more than once

**Comment by samleong123** [comment]
> you don't need to set nonce more than once

this will affect the downgrade to be failed? 
Now im back to IOS 15.4 and if can't drop then forever stay there
