### ISSUE TITLE
Make error: error: use of undeclared identifier 'PLIST_ERR_SUCCESS'

### ISSUE THREAD

**Issue by Harky911** [marijuanARM/futurerestore#73]
![IMAGE 2022-04-07 15:18:05](https://user-images.githubusercontent.com/15734496/162222333-f1fd81d6-ae63-42d0-a3db-bbbeb78d5144.jpg)

Mac M1 Big Sur v11.6.1

**Comment by Cryptiiiic** [comment]
No reason to compile this

**Comment by Harky911** [comment]
> No reason to compile this

After compiling libplist from source and installing it worked. But because ipwndfu doesn’t work on Mac m1 I can’t use.

Was trying to downgrade iPhone 8 on iOS 15 to 14.7 using Inferius

**Comment by Cryptiiiic** [comment]
No reason to compile this and you are probably missing stuff anyway there’s already an m1 binary also can’t fix the usbmuxd status issues on m1 no one has donated there m1 for remote diagnosis
