### ISSUE TITLE
external/idevicerestore won't build with new versions of libimobiledevice-glue

### ISSUE THREAD

**Issue by stek29** [marijuanARM/futurerestore#76]
it needs this commit:
https://github.com/libimobiledevice/idevicerestore/commit/f80a876b3598de4eb551bafcb279947c527fae33

**Comment by stek29** [comment]
i'm opening the issue here instead of futurerestore/idevicerestore repo since issues are disabled in it, and since this repo and build environments would have to be updated too.

**Comment by Cryptiiiic** [comment]
Commit is there I just committed the code inside my commit by accident, I can fix it and force push if you would like? Either way the commit is there.

**Comment by stek29** [comment]
@Cryptiiiic weird, it didn’t build for me with recent version of glue because of COLOR macros. should’ve checked better I guess, sorry :(

**Comment by Cryptiiiic** [comment]
Happens to me to, I always git stash, then rm –rf * then git reset hard then update gitmodules because I’m always paranoid of remnant files

**Comment by Cryptiiiic** [comment]
Accidentally reopened this yesterday apparently. However I just reverted the commit and merged with limd upstream so it has the real nikias commits :)
