### ISSUE TITLE
Unable to compile futurerestore due to color's

### ISSUE THREAD

**Issue by Merculous** [marijuanARM/futurerestore#79]
I'm unable to compile via Ubuntu. Apparently, this is an idevicerestore issue and it is fixed with this issue page https://github.com/libimobiledevice/idevicerestore/issues/489

Here's my error log https://pastebin.com/rHZCQ89X

**Comment by Cryptiiiic** [comment]
You are supposed to compile test branch and don’t forget to update libimobiledevice-glue
