### ISSUE TITLE
Getting "Unable to put device into restore mode" on iPhone 6s Plus n66ap (iOS 15.3)

### ISSUE THREAD

**Issue by HuyNguyenGia-3103** [marijuanARM/futurerestore#89]
Here's my log
[FRLog_2022-07-18T13.28.54.852500.txt](https://github.com/futurerestore/futurerestore/files/9129893/FRLog_2022-07-18T13.28.54.852500.txt)

**Comment by Cryptiiiic** [comment]
You need to pwn with gaster or eclipsa for pwndfu feature to work

**Comment by HuyNguyenGia-3103** [comment]
yes I did, I used ipwnder_lite

**Comment by Cryptiiiic** [comment]
It seems broken I tried it on my 6s. It failed. Use eclipsa/gaster it works.
