### ISSUE TITLE
Failed to find matching buildidentity

### ISSUE THREAD

**Issue by FeedMyBalls** [marijuanARM/futurerestore#91]
:( failed verification with error:
[exception]:
what=verification failed!
code=84279308
line=1286
file=img4tool.cpp
commit count=197:
commit sha  =aca6cf005c94caf135023263cbb5c61a0081804f:

**Comment by Cryptiiiic** [comment]
We always need the full context

**Comment by FeedMyBalls** [comment]
iphone se 2nd gen, a15. ios 15.6 going back to ios 14.8, 7, 5, 4, 3. So far none has worked.. Did everything :(

**Comment by HydrationMan** [comment]
Are you sure the ipsw is for your device. And is your nonce even set

**Comment by FeedMyBalls** [comment]
it is :(

**Comment by HydrationMan** [comment]
What is the ipsw name

**Comment by galaxy4627** [comment]
> it is :(

My brother in christ, are you sure that your blob matches the target version

**Comment by Cryptiiiic** [comment]
iPhone SE a15 is 3rd gen a13 is 2nd gen btw
