### ISSUE TITLE
[TSSC] parsing firmware.json failed

### ISSUE THREAD

**Issue by FreQRiDeR** [marijuanARM/futurerestore#92]
This seems to be a common issue. Curl timeout. Can someone fix this for people without fast internet? 
FR LOG:

[1] Help improve FutureRestore by sharing logs: Disabled
[2] Set previous FutureRestore download, /Users/terramoda/FutureRestoreGUI/extracted/futurerestore, to FutureRestore executable.
[3] Set /Users/terramoda/Desktop/DownGrade IOS/14.8/1482399979621670_iPhone9,1_d10ap_14.8-18H17_15400076bc4c35a7c8caefdcae5bda69c140a11bce870548f0862aac28c194cc.shsh2 to SHSH blob.
[4] Set /Users/terramoda/Desktop/DownGrade IOS/iPhone_4.7_P3_14.8_18H17_Restore.ipsw to target IPSW.
[5] Make sure to hit "trust" on your device if prompted!
FutureRestore GUI Log – 2022-08-21T20.04.06.310426
Command ran: /Users/terramoda/FutureRestoreGUI/extracted/futurerestore --apticket /Users/terramoda/Desktop/DownGrade IOS/14.8/1482399979621670_iPhone9,1_d10ap_14.8-18H17_15400076bc4c35a7c8caefdcae5bda69c140a11bce870548f0862aac28c194cc.shsh2 --debug --latest-sep --latest-baseband /Users/terramoda/Desktop/DownGrade IOS/iPhone_4.7_P3_14.8_18H17_Restore.ipsw 
Version: 0ab9df3209ee599f581532d05d331e6abe0f53f3 - 194
img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f
libipatcher version: 0.82-0b2f79ff0917ef9b8a92475d93d9466b23fc2322
Odysseus for 32-bit support: yes
Odysseus for 64-bit support: yes
INFO: device serial number is DNRSPCZKHG75
[INFO] 64-bit device detected
futurerestore init done
reading signing ticket /Users/terramoda/Desktop/DownGrade IOS/14.8/1482399979621670_iPhone9,1_d10ap_14.8-18H17_15400076bc4c35a7c8caefdcae5bda69c140a11bce870548f0862aac28c194cc.shsh2 is done
user specified to use latest signed SEP (WARNING, THIS CAN CAUSE A NON-WORKING RESTORE)
[TSSC] opening firmwares.json
[DOWN] downloading file https://api.ipsw.me/v2.1/firmwares.json/condensed
[Error] failed to download file from=https://api.ipsw.me/v2.1/firmwares.json/condensed to=/tmp/firmwares.json CURLcode=28
futurerestore: failed with exception:
[exception]:
what=[TSSC] parsing firmware.json failed

**Comment by FreQRiDeR** [comment]
I am able to download condensed.json manually. I tried renaming to firmware.json and placing it in /temp but it still prompts to download the file and overwrites it. Been trying for days now to downgrade :(

**Comment by FreQRiDeR** [comment]
Maybe this helps? 
https://stackoverflow.com/questions/46009413/express-adding-a-json-payload-with-curl-causing-parsing-error

**Comment by Cryptiiiic** [comment]
194 is not supported at all, use 290 or later

**Comment by FreQRiDeR** [comment]
194 is the gui version, I believe. I downloaded the latest beta.

**Comment by Cryptiiiic** [comment]
You did not and this is not gui support or support I general this is for bug reports. Which no bug here because this is an outdated version.
