### ISSUE TITLE
Can not downgrade to iOS14

### ISSUE THREAD

**Issue by Halo-Michael** [marijuanARM/futurerestore#96]
I'm using iPhone7 (iPhone9,1). I was on iOS14.3. I was try to upgrade to 14.8 with 15.6 sep, it success; and I also can downgrade to 14.3 using 15.6 sep. But I can't upgrade to 15.x. I was thought It's I got some thing wrong. Once I use Finder upgrade to 15.7, I can successful downgrade to 15.1 or 15.x! But I can't downgrade to 14.x anymore. Here is some log from v291, didn't save any older log.
![EDE537F4-A34F-4A79-B067-303E5C822D67](https://user-images.githubusercontent.com/45062120/192312805-7ae3d109-1a2b-4cc9-89b9-e8f5b9c2741d.png)

**Comment by Cryptiiiic** [comment]
Caching is broken in 291 it’s fixed in 292 however only the windows version has 292 as of now. Delete futurerestore cache and add –j to arguments

**Comment by Halo-Michael** [comment]
> Caching is broken in 291 it’s fixed in 292 however only the windows version has 292 as of now. Delete futurerestore cache and add –j to arguments 

How to delete futurerestore cache?

**Comment by Cryptiiiic** [comment]
/tmp/futurerestore

**Comment by vuong07** [comment]
> > Caching is broken in 291 it’s fixed in 292 however only the windows version has 292 as of now. Delete futurerestore cache and add –j to arguments
> 
> How to delete futurerestore cache?

I have the same error as above, please help me how to fix the error and the command to execute on terminal ubuntu is complete

**Comment by Cryptiiiic** [comment]
1. Do not manually specify sep and baseband
2. If your device supports iOS 16, you need to force custom latest beta for 15.7
3. -j for disable rsep command
4. post full log including command.
@vuong07

**Comment by Halo-Michael** [comment]
So here is the log with v297(652e1fada77efd1ba812d2c391e9f0fcd7fb0439). Now futurerestore is able to send filesystem but after that still fail.
Without -j is the same.

**Comment by Halo-Michael** [comment]
> So here is the log with v297([652e1fa](https://github.com/futurerestore/futurerestore/commit/652e1fada77efd1ba812d2c391e9f0fcd7fb0439)). Now futurerestore is able to send filesystem but after that still fail. Without -j is the same.

Update: Never mind, it's because I created another system volume. Now I can successful downgrade to iOS14.3.
